packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  react: ^19.2.7
  react-dom: ^19.2.7
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@tsdown/css': ^0.22.2
  '@vanilla-extract/css': ^1.20.1
  '@vanilla-extract/vite-plugin': ^5.2.2
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: set this to true or false
