/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ExamplesSlugRouteImport } from './routes/examples.$slug'
import { Route as DocsComponentsIndexRouteImport } from './routes/docs.components.index'
import { Route as DocsComponentsTodoRouteImport } from './routes/docs.components.todo'
import { Route as DocsComponentsSideNavRouteImport } from './routes/docs.components.side-nav'
import { Route as DocsComponentsSelectRouteImport } from './routes/docs.components.select'
import { Route as DocsComponentsRuneTextRouteImport } from './routes/docs.components.rune-text'
import { Route as DocsComponentsRocoThemeRouteImport } from './routes/docs.components.roco-theme'
import { Route as DocsComponentsRocoShapeRouteImport } from './routes/docs.components.roco-shape'
import { Route as DocsComponentsRadioGroupRouteImport } from './routes/docs.components.radio-group'
import { Route as DocsComponentsPanelRouteImport } from './routes/docs.components.panel'
import { Route as DocsComponentsModalRouteImport } from './routes/docs.components.modal'
import { Route as DocsComponentsMaterialRouteImport } from './routes/docs.components.material'
import { Route as DocsComponentsIconsRouteImport } from './routes/docs.components.icons'
import { Route as DocsComponentsDrawerRouteImport } from './routes/docs.components.drawer'
import { Route as DocsComponentsCheckboxRouteImport } from './routes/docs.components.checkbox'
import { Route as DocsComponentsButtonNormalRouteImport } from './routes/docs.components.button-normal'
import { Route as DocsComponentsButtonRouteImport } from './routes/docs.components.button'

const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ExamplesSlugRoute = ExamplesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamplesRoute,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsTodoRoute = DocsComponentsTodoRouteImport.update({
  id: '/components/todo',
  path: '/components/todo',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsSideNavRoute = DocsComponentsSideNavRouteImport.update({
  id: '/components/side-nav',
  path: '/components/side-nav',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsSelectRoute = DocsComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsRuneTextRoute = DocsComponentsRuneTextRouteImport.update({
  id: '/components/rune-text',
  path: '/components/rune-text',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsRocoThemeRoute = DocsComponentsRocoThemeRouteImport.update({
  id: '/components/roco-theme',
  path: '/components/roco-theme',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsRocoShapeRoute = DocsComponentsRocoShapeRouteImport.update({
  id: '/components/roco-shape',
  path: '/components/roco-shape',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsRadioGroupRoute =
  DocsComponentsRadioGroupRouteImport.update({
    id: '/components/radio-group',
    path: '/components/radio-group',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsPanelRoute = DocsComponentsPanelRouteImport.update({
  id: '/components/panel',
  path: '/components/panel',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsModalRoute = DocsComponentsModalRouteImport.update({
  id: '/components/modal',
  path: '/components/modal',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsMaterialRoute = DocsComponentsMaterialRouteImport.update({
  id: '/components/material',
  path: '/components/material',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsIconsRoute = DocsComponentsIconsRouteImport.update({
  id: '/components/icons',
  path: '/components/icons',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsDrawerRoute = DocsComponentsDrawerRouteImport.update({
  id: '/components/drawer',
  path: '/components/drawer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsCheckboxRoute = DocsComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsButtonNormalRoute =
  DocsComponentsButtonNormalRouteImport.update({
    id: '/components/button-normal',
    path: '/components/button-normal',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsButtonRoute = DocsComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/examples/$slug': typeof ExamplesSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/button-normal': typeof DocsComponentsButtonNormalRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/icons': typeof DocsComponentsIconsRoute
  '/docs/components/material': typeof DocsComponentsMaterialRoute
  '/docs/components/modal': typeof DocsComponentsModalRoute
  '/docs/components/panel': typeof DocsComponentsPanelRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/roco-shape': typeof DocsComponentsRocoShapeRoute
  '/docs/components/roco-theme': typeof DocsComponentsRocoThemeRoute
  '/docs/components/rune-text': typeof DocsComponentsRuneTextRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/side-nav': typeof DocsComponentsSideNavRoute
  '/docs/components/todo': typeof DocsComponentsTodoRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/examples/$slug': typeof ExamplesSlugRoute
  '/docs': typeof DocsIndexRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/button-normal': typeof DocsComponentsButtonNormalRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/icons': typeof DocsComponentsIconsRoute
  '/docs/components/material': typeof DocsComponentsMaterialRoute
  '/docs/components/modal': typeof DocsComponentsModalRoute
  '/docs/components/panel': typeof DocsComponentsPanelRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/roco-shape': typeof DocsComponentsRocoShapeRoute
  '/docs/components/roco-theme': typeof DocsComponentsRocoThemeRoute
  '/docs/components/rune-text': typeof DocsComponentsRuneTextRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/side-nav': typeof DocsComponentsSideNavRoute
  '/docs/components/todo': typeof DocsComponentsTodoRoute
  '/docs/components': typeof DocsComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/examples/$slug': typeof ExamplesSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/button-normal': typeof DocsComponentsButtonNormalRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/icons': typeof DocsComponentsIconsRoute
  '/docs/components/material': typeof DocsComponentsMaterialRoute
  '/docs/components/modal': typeof DocsComponentsModalRoute
  '/docs/components/panel': typeof DocsComponentsPanelRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/roco-shape': typeof DocsComponentsRocoShapeRoute
  '/docs/components/roco-theme': typeof DocsComponentsRocoThemeRoute
  '/docs/components/rune-text': typeof DocsComponentsRuneTextRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/side-nav': typeof DocsComponentsSideNavRoute
  '/docs/components/todo': typeof DocsComponentsTodoRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/examples'
    | '/examples/$slug'
    | '/docs/'
    | '/docs/components/button'
    | '/docs/components/button-normal'
    | '/docs/components/checkbox'
    | '/docs/components/drawer'
    | '/docs/components/icons'
    | '/docs/components/material'
    | '/docs/components/modal'
    | '/docs/components/panel'
    | '/docs/components/radio-group'
    | '/docs/components/roco-shape'
    | '/docs/components/roco-theme'
    | '/docs/components/rune-text'
    | '/docs/components/select'
    | '/docs/components/side-nav'
    | '/docs/components/todo'
    | '/docs/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples'
    | '/examples/$slug'
    | '/docs'
    | '/docs/components/button'
    | '/docs/components/button-normal'
    | '/docs/components/checkbox'
    | '/docs/components/drawer'
    | '/docs/components/icons'
    | '/docs/components/material'
    | '/docs/components/modal'
    | '/docs/components/panel'
    | '/docs/components/radio-group'
    | '/docs/components/roco-shape'
    | '/docs/components/roco-theme'
    | '/docs/components/rune-text'
    | '/docs/components/select'
    | '/docs/components/side-nav'
    | '/docs/components/todo'
    | '/docs/components'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/examples'
    | '/examples/$slug'
    | '/docs/'
    | '/docs/components/button'
    | '/docs/components/button-normal'
    | '/docs/components/checkbox'
    | '/docs/components/drawer'
    | '/docs/components/icons'
    | '/docs/components/material'
    | '/docs/components/modal'
    | '/docs/components/panel'
    | '/docs/components/radio-group'
    | '/docs/components/roco-shape'
    | '/docs/components/roco-theme'
    | '/docs/components/rune-text'
    | '/docs/components/select'
    | '/docs/components/side-nav'
    | '/docs/components/todo'
    | '/docs/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExamplesRoute: typeof ExamplesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/examples/$slug': {
      id: '/examples/$slug'
      path: '/$slug'
      fullPath: '/examples/$slug'
      preLoaderRoute: typeof ExamplesSlugRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/docs/components/': {
      id: '/docs/components/'
      path: '/components'
      fullPath: '/docs/components/'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/todo': {
      id: '/docs/components/todo'
      path: '/components/todo'
      fullPath: '/docs/components/todo'
      preLoaderRoute: typeof DocsComponentsTodoRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/side-nav': {
      id: '/docs/components/side-nav'
      path: '/components/side-nav'
      fullPath: '/docs/components/side-nav'
      preLoaderRoute: typeof DocsComponentsSideNavRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/select': {
      id: '/docs/components/select'
      path: '/components/select'
      fullPath: '/docs/components/select'
      preLoaderRoute: typeof DocsComponentsSelectRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/rune-text': {
      id: '/docs/components/rune-text'
      path: '/components/rune-text'
      fullPath: '/docs/components/rune-text'
      preLoaderRoute: typeof DocsComponentsRuneTextRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/roco-theme': {
      id: '/docs/components/roco-theme'
      path: '/components/roco-theme'
      fullPath: '/docs/components/roco-theme'
      preLoaderRoute: typeof DocsComponentsRocoThemeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/roco-shape': {
      id: '/docs/components/roco-shape'
      path: '/components/roco-shape'
      fullPath: '/docs/components/roco-shape'
      preLoaderRoute: typeof DocsComponentsRocoShapeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/radio-group': {
      id: '/docs/components/radio-group'
      path: '/components/radio-group'
      fullPath: '/docs/components/radio-group'
      preLoaderRoute: typeof DocsComponentsRadioGroupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/panel': {
      id: '/docs/components/panel'
      path: '/components/panel'
      fullPath: '/docs/components/panel'
      preLoaderRoute: typeof DocsComponentsPanelRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/modal': {
      id: '/docs/components/modal'
      path: '/components/modal'
      fullPath: '/docs/components/modal'
      preLoaderRoute: typeof DocsComponentsModalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/material': {
      id: '/docs/components/material'
      path: '/components/material'
      fullPath: '/docs/components/material'
      preLoaderRoute: typeof DocsComponentsMaterialRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/icons': {
      id: '/docs/components/icons'
      path: '/components/icons'
      fullPath: '/docs/components/icons'
      preLoaderRoute: typeof DocsComponentsIconsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/drawer': {
      id: '/docs/components/drawer'
      path: '/components/drawer'
      fullPath: '/docs/components/drawer'
      preLoaderRoute: typeof DocsComponentsDrawerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/checkbox': {
      id: '/docs/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/docs/components/checkbox'
      preLoaderRoute: typeof DocsComponentsCheckboxRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/button-normal': {
      id: '/docs/components/button-normal'
      path: '/components/button-normal'
      fullPath: '/docs/components/button-normal'
      preLoaderRoute: typeof DocsComponentsButtonNormalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/button': {
      id: '/docs/components/button'
      path: '/components/button'
      fullPath: '/docs/components/button'
      preLoaderRoute: typeof DocsComponentsButtonRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentsButtonRoute: typeof DocsComponentsButtonRoute
  DocsComponentsButtonNormalRoute: typeof DocsComponentsButtonNormalRoute
  DocsComponentsCheckboxRoute: typeof DocsComponentsCheckboxRoute
  DocsComponentsDrawerRoute: typeof DocsComponentsDrawerRoute
  DocsComponentsIconsRoute: typeof DocsComponentsIconsRoute
  DocsComponentsMaterialRoute: typeof DocsComponentsMaterialRoute
  DocsComponentsModalRoute: typeof DocsComponentsModalRoute
  DocsComponentsPanelRoute: typeof DocsComponentsPanelRoute
  DocsComponentsRadioGroupRoute: typeof DocsComponentsRadioGroupRoute
  DocsComponentsRocoShapeRoute: typeof DocsComponentsRocoShapeRoute
  DocsComponentsRocoThemeRoute: typeof DocsComponentsRocoThemeRoute
  DocsComponentsRuneTextRoute: typeof DocsComponentsRuneTextRoute
  DocsComponentsSelectRoute: typeof DocsComponentsSelectRoute
  DocsComponentsSideNavRoute: typeof DocsComponentsSideNavRoute
  DocsComponentsTodoRoute: typeof DocsComponentsTodoRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentsButtonRoute: DocsComponentsButtonRoute,
  DocsComponentsButtonNormalRoute: DocsComponentsButtonNormalRoute,
  DocsComponentsCheckboxRoute: DocsComponentsCheckboxRoute,
  DocsComponentsDrawerRoute: DocsComponentsDrawerRoute,
  DocsComponentsIconsRoute: DocsComponentsIconsRoute,
  DocsComponentsMaterialRoute: DocsComponentsMaterialRoute,
  DocsComponentsModalRoute: DocsComponentsModalRoute,
  DocsComponentsPanelRoute: DocsComponentsPanelRoute,
  DocsComponentsRadioGroupRoute: DocsComponentsRadioGroupRoute,
  DocsComponentsRocoShapeRoute: DocsComponentsRocoShapeRoute,
  DocsComponentsRocoThemeRoute: DocsComponentsRocoThemeRoute,
  DocsComponentsRuneTextRoute: DocsComponentsRuneTextRoute,
  DocsComponentsSelectRoute: DocsComponentsSelectRoute,
  DocsComponentsSideNavRoute: DocsComponentsSideNavRoute,
  DocsComponentsTodoRoute: DocsComponentsTodoRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ExamplesRouteChildren {
  ExamplesSlugRoute: typeof ExamplesSlugRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  ExamplesSlugRoute: ExamplesSlugRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  ExamplesRoute: ExamplesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
