/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ExamplesSlugRouteImport } from './routes/examples.$slug'
import { Route as DocsIconRouteImport } from './routes/docs.icon'
import { Route as DocsOverviewRocoThemeRouteImport } from './routes/docs.overview.roco-theme'
import { Route as DocsOverviewComponentsRouteImport } from './routes/docs.overview.components'
import { Route as DocsDesignRocoShapeRouteImport } from './routes/docs.design.roco-shape'
import { Route as DocsDesignMaterialRouteImport } from './routes/docs.design.material'
import { Route as DocsComponentsToggleGroupRouteImport } from './routes/docs.components.toggle-group'
import { Route as DocsComponentsSideNavRouteImport } from './routes/docs.components.side-nav'
import { Route as DocsComponentsSelectRouteImport } from './routes/docs.components.select'
import { Route as DocsComponentsRuneTextRouteImport } from './routes/docs.components.rune-text'
import { Route as DocsComponentsRadioGroupRouteImport } from './routes/docs.components.radio-group'
import { Route as DocsComponentsPanelRouteImport } from './routes/docs.components.panel'
import { Route as DocsComponentsModalRouteImport } from './routes/docs.components.modal'
import { Route as DocsComponentsDrawerRouteImport } from './routes/docs.components.drawer'
import { Route as DocsComponentsCheckboxRouteImport } from './routes/docs.components.checkbox'
import { Route as DocsComponentsButtonNormalRouteImport } from './routes/docs.components.button-normal'
import { Route as DocsComponentsButtonRouteImport } from './routes/docs.components.button'

const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ExamplesSlugRoute = ExamplesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamplesRoute,
} as any)
const DocsIconRoute = DocsIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOverviewRocoThemeRoute = DocsOverviewRocoThemeRouteImport.update({
  id: '/overview/roco-theme',
  path: '/overview/roco-theme',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOverviewComponentsRoute = DocsOverviewComponentsRouteImport.update({
  id: '/overview/components',
  path: '/overview/components',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDesignRocoShapeRoute = DocsDesignRocoShapeRouteImport.update({
  id: '/design/roco-shape',
  path: '/design/roco-shape',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDesignMaterialRoute = DocsDesignMaterialRouteImport.update({
  id: '/design/material',
  path: '/design/material',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsToggleGroupRoute =
  DocsComponentsToggleGroupRouteImport.update({
    id: '/components/toggle-group',
    path: '/components/toggle-group',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsSideNavRoute = DocsComponentsSideNavRouteImport.update({
  id: '/components/side-nav',
  path: '/components/side-nav',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsSelectRoute = DocsComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsRuneTextRoute = DocsComponentsRuneTextRouteImport.update({
  id: '/components/rune-text',
  path: '/components/rune-text',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsRadioGroupRoute =
  DocsComponentsRadioGroupRouteImport.update({
    id: '/components/radio-group',
    path: '/components/radio-group',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsPanelRoute = DocsComponentsPanelRouteImport.update({
  id: '/components/panel',
  path: '/components/panel',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsModalRoute = DocsComponentsModalRouteImport.update({
  id: '/components/modal',
  path: '/components/modal',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsDrawerRoute = DocsComponentsDrawerRouteImport.update({
  id: '/components/drawer',
  path: '/components/drawer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsCheckboxRoute = DocsComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsButtonNormalRoute =
  DocsComponentsButtonNormalRouteImport.update({
    id: '/components/button-normal',
    path: '/components/button-normal',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComponentsButtonRoute = DocsComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/docs/icon': typeof DocsIconRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/button-normal': typeof DocsComponentsButtonNormalRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/modal': typeof DocsComponentsModalRoute
  '/docs/components/panel': typeof DocsComponentsPanelRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/rune-text': typeof DocsComponentsRuneTextRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/side-nav': typeof DocsComponentsSideNavRoute
  '/docs/components/toggle-group': typeof DocsComponentsToggleGroupRoute
  '/docs/design/material': typeof DocsDesignMaterialRoute
  '/docs/design/roco-shape': typeof DocsDesignRocoShapeRoute
  '/docs/overview/components': typeof DocsOverviewComponentsRoute
  '/docs/overview/roco-theme': typeof DocsOverviewRocoThemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/docs/icon': typeof DocsIconRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/docs': typeof DocsIndexRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/button-normal': typeof DocsComponentsButtonNormalRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/modal': typeof DocsComponentsModalRoute
  '/docs/components/panel': typeof DocsComponentsPanelRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/rune-text': typeof DocsComponentsRuneTextRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/side-nav': typeof DocsComponentsSideNavRoute
  '/docs/components/toggle-group': typeof DocsComponentsToggleGroupRoute
  '/docs/design/material': typeof DocsDesignMaterialRoute
  '/docs/design/roco-shape': typeof DocsDesignRocoShapeRoute
  '/docs/overview/components': typeof DocsOverviewComponentsRoute
  '/docs/overview/roco-theme': typeof DocsOverviewRocoThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/docs/icon': typeof DocsIconRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/button-normal': typeof DocsComponentsButtonNormalRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/drawer': typeof DocsComponentsDrawerRoute
  '/docs/components/modal': typeof DocsComponentsModalRoute
  '/docs/components/panel': typeof DocsComponentsPanelRoute
  '/docs/components/radio-group': typeof DocsComponentsRadioGroupRoute
  '/docs/components/rune-text': typeof DocsComponentsRuneTextRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/side-nav': typeof DocsComponentsSideNavRoute
  '/docs/components/toggle-group': typeof DocsComponentsToggleGroupRoute
  '/docs/design/material': typeof DocsDesignMaterialRoute
  '/docs/design/roco-shape': typeof DocsDesignRocoShapeRoute
  '/docs/overview/components': typeof DocsOverviewComponentsRoute
  '/docs/overview/roco-theme': typeof DocsOverviewRocoThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/examples'
    | '/docs/icon'
    | '/examples/$slug'
    | '/docs/'
    | '/docs/components/button'
    | '/docs/components/button-normal'
    | '/docs/components/checkbox'
    | '/docs/components/drawer'
    | '/docs/components/modal'
    | '/docs/components/panel'
    | '/docs/components/radio-group'
    | '/docs/components/rune-text'
    | '/docs/components/select'
    | '/docs/components/side-nav'
    | '/docs/components/toggle-group'
    | '/docs/design/material'
    | '/docs/design/roco-shape'
    | '/docs/overview/components'
    | '/docs/overview/roco-theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples'
    | '/docs/icon'
    | '/examples/$slug'
    | '/docs'
    | '/docs/components/button'
    | '/docs/components/button-normal'
    | '/docs/components/checkbox'
    | '/docs/components/drawer'
    | '/docs/components/modal'
    | '/docs/components/panel'
    | '/docs/components/radio-group'
    | '/docs/components/rune-text'
    | '/docs/components/select'
    | '/docs/components/side-nav'
    | '/docs/components/toggle-group'
    | '/docs/design/material'
    | '/docs/design/roco-shape'
    | '/docs/overview/components'
    | '/docs/overview/roco-theme'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/examples'
    | '/docs/icon'
    | '/examples/$slug'
    | '/docs/'
    | '/docs/components/button'
    | '/docs/components/button-normal'
    | '/docs/components/checkbox'
    | '/docs/components/drawer'
    | '/docs/components/modal'
    | '/docs/components/panel'
    | '/docs/components/radio-group'
    | '/docs/components/rune-text'
    | '/docs/components/select'
    | '/docs/components/side-nav'
    | '/docs/components/toggle-group'
    | '/docs/design/material'
    | '/docs/design/roco-shape'
    | '/docs/overview/components'
    | '/docs/overview/roco-theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExamplesRoute: typeof ExamplesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/examples/$slug': {
      id: '/examples/$slug'
      path: '/$slug'
      fullPath: '/examples/$slug'
      preLoaderRoute: typeof ExamplesSlugRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/docs/icon': {
      id: '/docs/icon'
      path: '/icon'
      fullPath: '/docs/icon'
      preLoaderRoute: typeof DocsIconRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/overview/roco-theme': {
      id: '/docs/overview/roco-theme'
      path: '/overview/roco-theme'
      fullPath: '/docs/overview/roco-theme'
      preLoaderRoute: typeof DocsOverviewRocoThemeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/overview/components': {
      id: '/docs/overview/components'
      path: '/overview/components'
      fullPath: '/docs/overview/components'
      preLoaderRoute: typeof DocsOverviewComponentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/design/roco-shape': {
      id: '/docs/design/roco-shape'
      path: '/design/roco-shape'
      fullPath: '/docs/design/roco-shape'
      preLoaderRoute: typeof DocsDesignRocoShapeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/design/material': {
      id: '/docs/design/material'
      path: '/design/material'
      fullPath: '/docs/design/material'
      preLoaderRoute: typeof DocsDesignMaterialRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/toggle-group': {
      id: '/docs/components/toggle-group'
      path: '/components/toggle-group'
      fullPath: '/docs/components/toggle-group'
      preLoaderRoute: typeof DocsComponentsToggleGroupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/side-nav': {
      id: '/docs/components/side-nav'
      path: '/components/side-nav'
      fullPath: '/docs/components/side-nav'
      preLoaderRoute: typeof DocsComponentsSideNavRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/select': {
      id: '/docs/components/select'
      path: '/components/select'
      fullPath: '/docs/components/select'
      preLoaderRoute: typeof DocsComponentsSelectRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/rune-text': {
      id: '/docs/components/rune-text'
      path: '/components/rune-text'
      fullPath: '/docs/components/rune-text'
      preLoaderRoute: typeof DocsComponentsRuneTextRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/radio-group': {
      id: '/docs/components/radio-group'
      path: '/components/radio-group'
      fullPath: '/docs/components/radio-group'
      preLoaderRoute: typeof DocsComponentsRadioGroupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/panel': {
      id: '/docs/components/panel'
      path: '/components/panel'
      fullPath: '/docs/components/panel'
      preLoaderRoute: typeof DocsComponentsPanelRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/modal': {
      id: '/docs/components/modal'
      path: '/components/modal'
      fullPath: '/docs/components/modal'
      preLoaderRoute: typeof DocsComponentsModalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/drawer': {
      id: '/docs/components/drawer'
      path: '/components/drawer'
      fullPath: '/docs/components/drawer'
      preLoaderRoute: typeof DocsComponentsDrawerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/checkbox': {
      id: '/docs/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/docs/components/checkbox'
      preLoaderRoute: typeof DocsComponentsCheckboxRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/button-normal': {
      id: '/docs/components/button-normal'
      path: '/components/button-normal'
      fullPath: '/docs/components/button-normal'
      preLoaderRoute: typeof DocsComponentsButtonNormalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/button': {
      id: '/docs/components/button'
      path: '/components/button'
      fullPath: '/docs/components/button'
      preLoaderRoute: typeof DocsComponentsButtonRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsIconRoute: typeof DocsIconRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentsButtonRoute: typeof DocsComponentsButtonRoute
  DocsComponentsButtonNormalRoute: typeof DocsComponentsButtonNormalRoute
  DocsComponentsCheckboxRoute: typeof DocsComponentsCheckboxRoute
  DocsComponentsDrawerRoute: typeof DocsComponentsDrawerRoute
  DocsComponentsModalRoute: typeof DocsComponentsModalRoute
  DocsComponentsPanelRoute: typeof DocsComponentsPanelRoute
  DocsComponentsRadioGroupRoute: typeof DocsComponentsRadioGroupRoute
  DocsComponentsRuneTextRoute: typeof DocsComponentsRuneTextRoute
  DocsComponentsSelectRoute: typeof DocsComponentsSelectRoute
  DocsComponentsSideNavRoute: typeof DocsComponentsSideNavRoute
  DocsComponentsToggleGroupRoute: typeof DocsComponentsToggleGroupRoute
  DocsDesignMaterialRoute: typeof DocsDesignMaterialRoute
  DocsDesignRocoShapeRoute: typeof DocsDesignRocoShapeRoute
  DocsOverviewComponentsRoute: typeof DocsOverviewComponentsRoute
  DocsOverviewRocoThemeRoute: typeof DocsOverviewRocoThemeRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIconRoute: DocsIconRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentsButtonRoute: DocsComponentsButtonRoute,
  DocsComponentsButtonNormalRoute: DocsComponentsButtonNormalRoute,
  DocsComponentsCheckboxRoute: DocsComponentsCheckboxRoute,
  DocsComponentsDrawerRoute: DocsComponentsDrawerRoute,
  DocsComponentsModalRoute: DocsComponentsModalRoute,
  DocsComponentsPanelRoute: DocsComponentsPanelRoute,
  DocsComponentsRadioGroupRoute: DocsComponentsRadioGroupRoute,
  DocsComponentsRuneTextRoute: DocsComponentsRuneTextRoute,
  DocsComponentsSelectRoute: DocsComponentsSelectRoute,
  DocsComponentsSideNavRoute: DocsComponentsSideNavRoute,
  DocsComponentsToggleGroupRoute: DocsComponentsToggleGroupRoute,
  DocsDesignMaterialRoute: DocsDesignMaterialRoute,
  DocsDesignRocoShapeRoute: DocsDesignRocoShapeRoute,
  DocsOverviewComponentsRoute: DocsOverviewComponentsRoute,
  DocsOverviewRocoThemeRoute: DocsOverviewRocoThemeRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ExamplesRouteChildren {
  ExamplesSlugRoute: typeof ExamplesSlugRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  ExamplesSlugRoute: ExamplesSlugRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  ExamplesRoute: ExamplesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
